/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4e3aea6070ddfdc350754f4ee19bfab2)
interface __BaseEnv_Env {
	LOTTO_RAW: R2Bucket;
	LOTTO_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
