import { tradingEngineObjectName } from "../utils/TradingEngineStub";
import type { EdgeTopology, Env } from "../types";
import { json } from "./ResponseHelpers";

export const ROUTE_CATALOG = [
  "GET /health",
  "GET /state (TELEMETRY:READ token)",
  "GET /performance (TELEMETRY:READ token)",
  "GET /metrics/performance (TELEMETRY:READ token)",
  "GET /slippage (TELEMETRY:READ token)",
  "GET /book/snapshot (TELEMETRY:READ token)",
  "GET /dom/heatmap (TELEMETRY:READ token)",
  "GET /liquidations/heatmap (TELEMETRY:READ token)",
  "GET /stream (TELEMETRY:READ token, WebSocket)",
  "POST /tick",
  "POST /hyperliquid/raw",
  "POST /liquidation",
  "POST /market/tick",
  "GET /market/ws",
  "POST /agent/signal",
  "GET /moltworker/health",
  "POST /login",
  "GET /admin",
  "GET /admin/ui",
  "GET|POST|PUT|PATCH /admin/config",
  "GET /admin/health",
  "GET /admin/state",
  "GET /admin/settings",
  "GET /admin/diagnostics",
  "GET /admin/live-readiness",
  "POST /admin/live-readiness/approve",
  "POST /admin/auth/revoke",
  "POST /admin/auth/revoke-all-for-subject",
  "GET /admin/auth/revoked",
  "POST /admin/moltworker/heartbeat",
  "POST /admin/settings/notifications",
  "GET|POST /admin/topology/calibrate",
  "GET /admin/performance",
  "GET /admin/metrics/performance",
  "POST /admin/maintenance/prune-logs",
  "POST /admin/maintenance/recover",
  "GET /admin/slippage",
  "GET /admin/history",
  "GET /admin/trace",
  "GET /admin/attribution",
  "GET /admin/alerts",
  "POST /admin/alerts/test",
  "POST /admin/replay",
  "GET /admin/replay/status",
  "GET|POST /admin/vault",
  "POST /admin/vault/test",
  "POST /admin/news/sentiment",
  "POST /admin/news/blackout",
  "GET /admin/cascade/active",
  "GET /admin/cascade/signals",
  "GET /admin/cascade/positions",
  "POST /admin/cascade/positions/:id/close",
  "POST /admin/cascade/blackout",
  "GET /admin/cascade/heat",
  "POST /admin/backtest/cascade",
  "GET /admin/book/snapshot",
  "GET /admin/dom/heatmap",
  "GET /admin/liquidations/heatmap",
  "GET /admin/stream",
  "GET /admin/logs",
  "GET /admin/congress/status",
  "GET /admin/congress/runs",
  "POST /admin/congress/run",
  "POST /admin/congress/ingest",
  "GET /admin/congress/filings",
  "GET /admin/congress/tickers",
  "GET /admin/congress/macro",
  "GET /admin/congress/transactions",
  "POST /admin/congress/pnl/refresh",
  "POST /admin/congress/options/backfill",
  "GET /admin/congress/alpha",
  "POST /admin/congress/alpha/run"
] as const;

export function gatewayCatalogResponse(env: Env, topology: EdgeTopology): Response {
  return json({
    ok: true,
    service: "sovereign-sigma-core",
    singleton: tradingEngineObjectName(env),
    topology,
    routes: ROUTE_CATALOG
  });
}
