/* Auto-generated by npm run proto:compile. Do not edit by hand. */
export const hyperliquidGrpcDescriptor = {
  "nested": {
    "hyperliquid_l1_gateway": {
      "nested": {
        "v2": {
          "nested": {
            "HyperliquidL1Gateway": {
              "methods": {
                "StreamBlocks": {
                  "requestType": "Position",
                  "responseType": "Block",
                  "responseStream": true
                },
                "StreamFills": {
                  "requestType": "Position",
                  "responseType": "BlockFills",
                  "responseStream": true
                },
                "StreamOrderbookSnapshots": {
                  "requestType": "Position",
                  "responseType": "OrderBookSnapshot",
                  "responseStream": true
                },
                "GetBlock": {
                  "requestType": "Position",
                  "responseType": "Block"
                },
                "GetFills": {
                  "requestType": "Position",
                  "responseType": "BlockFills"
                },
                "GetOrderBookSnapshot": {
                  "requestType": "Timestamp",
                  "responseType": "OrderBookSnapshot"
                }
              }
            },
            "Position": {
              "oneofs": {
                "position": {
                  "oneof": [
                    "timestampMs",
                    "blockHeight"
                  ]
                }
              },
              "fields": {
                "timestampMs": {
                  "type": "int64",
                  "id": 1
                },
                "blockHeight": {
                  "type": "int64",
                  "id": 2
                }
              }
            },
            "Timestamp": {
              "fields": {
                "timestampMs": {
                  "type": "int64",
                  "id": 1
                }
              }
            },
            "Block": {
              "fields": {
                "data": {
                  "type": "bytes",
                  "id": 1
                }
              }
            },
            "OrderBookSnapshot": {
              "fields": {
                "data": {
                  "type": "bytes",
                  "id": 1
                }
              }
            },
            "BlockFills": {
              "fields": {
                "data": {
                  "type": "bytes",
                  "id": 1
                }
              }
            }
          }
        }
      }
    }
  }
} as const;

export const hyperliquidGrpcProtoFiles = [
  "proto/hyperliquid/dwellir_l1_gateway.proto"
] as const;

export const hyperliquidGrpcGeneratedAt = "2026-05-16T03:32:50.414Z" as const;

export function hasHyperliquidGrpcDescriptor(): boolean {
  return Object.keys(hyperliquidGrpcDescriptor.nested ?? {}).length > 0;
}
