/* Auto-generated by npm run proto:compile. Do not edit by hand. */
export const hyperliquidGrpcDescriptor = {
  "nested": {}
} as const;

export const hyperliquidGrpcProtoFiles = [] as const;

export const hyperliquidGrpcGeneratedAt = "2026-05-16T03:20:47.952Z" as const;

export function hasHyperliquidGrpcDescriptor(): boolean {
  return Object.keys(hyperliquidGrpcDescriptor.nested ?? {}).length > 0;
}
