import { existsSync } from "node:fs";
import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import protobuf from "protobufjs";

const rootDir = process.cwd();
const protoDir = path.join(rootDir, "proto", "hyperliquid");
const outDir = path.join(rootDir, "src", "types", "grpc");
const outFile = path.join(outDir, "hyperliquid.ts");

async function listProtoFiles(dir) {
  let entries = [];

  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch (error) {
    if (error && error.code === "ENOENT") {
      return [];
    }
    throw error;
  }

  const files = [];
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listProtoFiles(fullPath)));
      continue;
    }
    if (entry.isFile() && entry.name.endsWith(".proto")) {
      files.push(fullPath);
    }
  }

  return files.sort();
}

function relativeProtoPath(file) {
  return path.relative(rootDir, file).split(path.sep).join("/");
}

async function compile(files) {
  const root = new protobuf.Root();
  root.resolvePath = (origin, target) => {
    const candidates = [
      origin ? path.resolve(path.dirname(origin), target) : path.resolve(protoDir, target),
      path.resolve(protoDir, target),
      path.resolve(rootDir, target)
    ];

    return candidates.find((candidate) => existsSync(candidate)) ?? path.resolve(protoDir, target);
  };

  await root.load(files, { keepCase: false });
  root.resolveAll();
  return root.toJSON();
}

async function main() {
  await mkdir(protoDir, { recursive: true });
  await mkdir(outDir, { recursive: true });

  const files = await listProtoFiles(protoDir);
  const descriptor = files.length > 0 ? await compile(files) : { nested: {} };
  const generatedAt = new Date().toISOString();
  const relativeFiles = files.map(relativeProtoPath);
  const source = `/* Auto-generated by npm run proto:compile. Do not edit by hand. */
export const hyperliquidGrpcDescriptor = ${JSON.stringify(descriptor, null, 2)} as const;

export const hyperliquidGrpcProtoFiles = ${JSON.stringify(relativeFiles, null, 2)} as const;

export const hyperliquidGrpcGeneratedAt = ${JSON.stringify(generatedAt)} as const;

export function hasHyperliquidGrpcDescriptor(): boolean {
  return Object.keys(hyperliquidGrpcDescriptor.nested ?? {}).length > 0;
}
`;

  await writeFile(outFile, source);
  console.log(
    files.length > 0
      ? `Compiled ${files.length} Hyperliquid proto file(s) into ${relativeProtoPath(outFile)}`
      : `No Hyperliquid proto files found; wrote placeholder ${relativeProtoPath(outFile)}`
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
