export const ENGINE_STATE_KEY = "engine:state";
export const ORDER_BOOK_PREFIX = "book:";
export const PERFORMANCE_HISTORY_KEY = "performance:latency-history";
export const CASCADE_POSITIONS_KEY = "cascade:positions";
export const CASCADE_PAPER_ARMED_AT_KEY = "cascade:paper_armed_at";
export const CASCADE_LAST_BACKTEST_REPORT_KEY = "cascade:last_backtest_report";
export const REPLAY_STATUS_KEY = "replay:status";
export const RISK_LIMITS_KEY = "risk:limits";
export const CONFIG_KEY = "engine:config";
export const DEFAULT_MAX_LATENCY_MS = 250;
export const DEFAULT_NATIVE_HL_MAX_LATENCY_MS = 150;
export const DEFAULT_DWELLIR_NATIVE_HL_MAX_LATENCY_MS = 2_500;
export const DEFAULT_HARD_STALE_DROP_MS = 1_000;
export const DEFAULT_HL_BOOK_TIMESTAMP_MAX_DRIFT_MS = 100;
export const DEFAULT_HL_SEQUENCE_GAP_MS = 5_000;
export const PERFORMANCE_HISTORY_LIMIT = 100;
export const CONFIG_ALARM_INTERVAL_MS = 5_000;
export const WARM_UP_INTERVAL_MS = 60_000;
export const SIGNAL_BUFFER_LIMIT = 500;
export const DEFAULT_TELEMETRY_FLUSH_INTERVAL_MS = 30_000;
export const TELEMETRY_BUFFER_LIMIT = 1_000;
export const ADMIN_STREAM_PULSE_INTERVAL_MS = 500;
export const AGENT_SNAPSHOT_TICK_INTERVAL = 1_000;
export const DEFAULT_HOT_STORAGE_SNAPSHOT_INTERVAL_MS = 60_000;
export const DEFAULT_HOT_STORAGE_SNAPSHOT_TICK_INTERVAL = 5_000;
export const STORAGE_WRITE_BACKOFF_MS = 60_000;
export const BOOK_SNAPSHOT_TOP_LEVELS = 100;
export const TOP_OF_BOOK_CROSS_CHECK_INTERVAL_MS = 60_000;
export const DEFAULT_SOURCE_WEIGHT = 1;
export const DEFAULT_PROFILER_BUCKET_VOLUME = 10;
export const DEFAULT_PROFILER_ROLLING_WINDOW = 50;
export const DEFAULT_PROFILER_ALERT_THRESHOLD = 0.7;
export const PROCESSING_LATENCY_SAMPLES_KEY = "performance:processing-latency-samples";
export const DOM_WALL_HISTORY_KEY = "dom:wall-history";
export const RATE_LIMIT_STATE_KEY = "execution:rate-limits";
export const EXECUTION_QUEUE_KEY = "execution:deferred-queue";
export const PAPER_SESSION_STARTED_AT_KEY = "paper:session_started_at";
export const HOT_PATH_LOG_THROTTLE_MS = 60_000;
export const DEFAULT_JITTER_SAMPLE_WINDOW = 1_000;
export const DEFAULT_JITTER_COMPUTE_INTERVAL_TICKS = 50;
export const DEFAULT_JITTER_THRESHOLD_MS = 10;
export const COLD_START_WAKEUP_THRESHOLD_MS = 25;
export const DEFAULT_DOM_PRICE_BIN_SIZE = 10;
export const DEFAULT_DOM_SCAN_RANGE_PCT = 0.02;
export const DEFAULT_DOM_WALL_HISTORY_LIMIT = 500;
export const DEFAULT_DOM_SPOOF_PROXIMITY_BPS = 15;
export const DOM_MAX_LEVELS_PER_SIDE = 2_000;
export const DEFAULT_ANOMALY_PRICE_Z_THRESHOLD = 6;
export const DEFAULT_ANOMALY_VOLUME_Z_THRESHOLD = 5;
export const DEFAULT_ANOMALY_CANCEL_EXEC_RATIO_THRESHOLD = 8;
export const DEFAULT_ANOMALY_PRICE_WINDOW_MS = 60_000;
export const DEFAULT_ANOMALY_VOLUME_WINDOW_MS = 600_000;
export const DEFAULT_ANOMALY_TOP_OF_BOOK_WINDOW_MS = 600_000;
export const DEFAULT_EXCHANGE_FEE_BPS = 5;
export const DEFAULT_MIN_EV_THRESHOLD = 0;
export const DEFAULT_MAX_POSITION_PCT = 0.05;
export const DEFAULT_MAX_INVENTORY_UNITS = 5;
export const DEFAULT_MAX_INVENTORY_DELTA = 1;
export const DEFAULT_RISK_AVERSION_FACTOR = 0.01;
export const DEFAULT_FUNDING_BIAS_THRESHOLD = 0.00001;
export const DEFAULT_FUNDING_INVENTORY_BIAS = 0;
export const DEFAULT_AMM_MIN_TICK_CHANGE = 0.00000001;
export const DEFAULT_HEATMAP_PRICE_BIN_SIZE = 100;
export const DEFAULT_HEATMAP_CLUSTER_NOTIONAL_USD = 10_000_000;
export const DEFAULT_CASCADE_DISTANCE_PCT = 0.005;
export const DEFAULT_PREDATORY_ORDER_OFFSET_BPS = 2;
export const DEFAULT_WHALE_PRINT_Z_THRESHOLD = 5;
export const DEFAULT_QUOTE_HIBERNATE_MS = 3_000;
export const DEFAULT_PAPER_BANKROLL_USD = 5_000;
export const DEFAULT_PAPER_MAX_GHOST_FILLS_PER_MINUTE = 90;
export const DEFAULT_PAPER_FILL_PARTICIPATION_RATE = 0.35;
export const DEFAULT_PAPER_FILL_ADVERSE_BPS = 1.5;
export const DEFAULT_PAPER_MAKER_FEE_BPS = 2;
export const DEFAULT_QUOTE_REFRESH_MIN_INTERVAL_MS = 750;
export const DEFAULT_QUOTE_REFRESH_MIN_PRICE_TICKS = 1;
export const DEFAULT_CROSS_ASSET_CANCEL_LEAD_BPS = 8;
export const DEFAULT_CROSS_ASSET_CANCEL_COOLDOWN_MS = 5_000;
export const DEFAULT_MARKET_TICK_JOURNAL_INTERVAL = 100;
export const DEFAULT_MARKET_TICK_MAX_ROWS = 100_000;
export const DEFAULT_SHADOW_VLO_CAPACITY = 512;
export const DEFAULT_SHADOW_VLO_DRIFT_TRADES = 3;
export const DEFAULT_SHADOW_VLO_QUEUE_DEPTH_MULTIPLIER = 1;
export const DEFAULT_SHADOW_VLO_BASE_SPREAD_BPS = 1;
export const DEFAULT_SHADOW_VLO_LATENCY_BUDGET_MS = 5;
export const DEFAULT_SHADOW_VLO_MIN_SIZE = 0.00000001;
export const DEFAULT_SHADOW_QUEUE_NO_EDGE_LOG_INTERVAL_MS = 60_000;
export const DEFAULT_VAR_CONFIDENCE_Z = 2.326;
export const TARGET_ASSET_MATRIX = [
  { coin: "BTC", instrumentCode: "btc-usd" },
  { coin: "HYPE", instrumentCode: "hype-usd" }
] as const;
export const TARGET_INSTRUMENTS = new Set<string>(
  TARGET_ASSET_MATRIX.map((asset) => asset.instrumentCode)
);
export const DEFAULT_JANITOR_INTERVAL_MS = 60_000;
export const DEFAULT_ORDER_ACK_TIMEOUT_MS = 2_000;
export const AGGREGATED_BUS_TELEMETRY_TYPES = new Set([
  "POST_QUOTE",
  "PULL_ALL_QUOTES",
  "STALE_DATA_KILL_SWITCH",
  "SUSPEND_QUOTES",
  "RESUME_QUOTES",
  "SHADOW_QUEUE_NO_EDGE",
  "SHADOW_QUEUE_GHOST_FILL",
  "SHADOW_QUEUE_GREEN_LIGHT",
  "SHADOW_QUEUE_RED_LIGHT",
  "SHADOW_QUEUE_SIGNAL_SUPPRESSED",
  "SHADOW_QUEUE_LATENCY_BREACH"
]);
